package utils

const (

	OPERATION_FLAG = "op"
	OPTION_FLAG = "o"
	TITLE_FLAG = "t"
	USERNAME_FLAG = "u"
	PASSWORD_FLAG = "p"
	PASSWORD_LENGTH_FLAG = "l"

	DEFAULT_OPERATION = "GET"
	DEFAULT_OPTION = "ALL"
	DEFAULT_TITLE = ""
	DEFAULT_USERNAME = ""
	DEFAULT_PASSWORD = ""
	DEFAULT_PASSWORD_LENGTH = 8

	GET_OPERATION = "GET"
	POST_OPERATION = "POST"
	PUT_OPERATION = "PUT"
	DELETE_OPERATION = "DELETE"

	ALL_OPTION = "ALL"

)